module.exports = {
  'compiler.beforeRun': 'Compilation starting...',
  'compiler.run': 'running',
  'compiler.watchRun': 'Compilation starting...',
  'compiler.beforeCompile': 'before compiling',
  'compiler.compile': 'compiling',
  'compiler.compilation': 'compilation',
  'compiler.emit': 'emit',
  'compiler.done': 'Compilation finished',
  'compiler.failed': 'failed',
  'compiler.invalid': 'invalid',
  'compiler.watchClose': 'watch closed',
  'compilation.finishModules': 'finish module graph',
  'compilation.seal': 'sealing',
  'compilation.beforeChunks': 'chunk graph',
  'compilation.afterChunks': 'after chunk graph',
  // "compilation.optimizeDependenciesBasic": // DEPRECATED v5
  'compilation.optimizeDependencies': 'dependencies optimization',
  // "compilation.optimizeDependenciesAdvanced": // DEPRECATED v5
  'compilation.afterOptimizeDependencies': 'after dependencies optimization',
  'compilation.optimize': 'optimizing',
  'compilation.optimizeModulesBasic': 'basic module optimization',
  'compilation.optimizeModules': 'module optimization',
  'compilation.optimizeModulesAdvanced': 'advanced module optimization',
  'compilation.afterOptimizeModules': 'after module optimization',
  'compilation.optimizeChunksBasic': 'basic chunk optimization',
  'compilation.optimizeChunks': 'chunk optimization',
  'compilation.optimizeChunksAdvanced': 'advanced chunk optimization',
  'compilation.afterOptimizeChunks': 'after chunk optimization',
  'compilation.optimizeTree': 'module and chunk tree optimization',
  'compilation.afterOptimizeTree': 'after module and chunk tree optimization',
  'compilation.optimizeChunkModulesBasic': 'basic chunk modules optimization',
  'compilation.optimizeChunkModules': 'chunk modules optimization',
  'compilation.optimizeChunkModulesAdvanced':
    'advanced chunk modules optimization',
  'compilation.afterOptimizeChunkModules': 'after chunk modules optimization',
  'compilation.reviveModules': 'module reviving',
  // "compilation.optimizeModuleOrder": // DEPRECATED v5
  // "compilation.advancedOptimizeModuleOrder": // DEPRECATED v5
  'compilation.beforeModuleIds': 'before module ids',
  'compilation.moduleIds': 'module ids',
  'compilation.optimizeModuleIds': 'module id optimization',
  'compilation.afterOptimizeModuleIds': 'module id optimization',
  'compilation.reviveChunks': 'chunk reviving',
  // "compilation.optimizeChunkOrder": // DEPRECATED v5
  'compilation.beforeChunkIds': 'before chunk ids',
  'compilation.optimizeChunkIds': 'chunk id optimization',
  'compilation.afterOptimizeChunkIds': 'after chunk id optimization',
  'compilation.recordModules': 'record modules',
  'compilation.recordChunks': 'record chunks',
  'compilation.beforeHash': 'hashing',
  'compilation.contentHash': 'content hashing',
  'compilation.afterHash': 'after hashing',
  'compilation.recordHash': 'record hash',
  'compilation.beforeModuleAssets': 'module assets processing',
  'compilation.beforeChunkAssets': 'chunk assets processing',
  'compilation.additionalChunkAssets': 'additional chunk assets processing',
  'compilation.record': 'recording',
  'compilation.additionalAssets': 'additional asset processing',
  'compilation.optimizeChunkAssets': 'chunk asset optimization',
  'compilation.afterOptimizeChunkAssets': 'after chunk asset optimization',
  'compilation.optimizeAssets': 'asset optimization',
  'compilation.afterOptimizeAssets': 'after asset optimization',
  'compilation.afterSeal': 'after seal',
};
